# Generated by Django 4.2.23 on 2025-09-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_skills', '0007_alter_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskills',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
