# Generated by Django 4.2.23 on 2025-09-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_skills', '0008_userskills_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
