# Generated by Django 4.2.23 on 2025-09-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_skills', '0009_skills_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
