# Generated by Django 4.2.23 on 2025-09-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_university_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
